### ISSUE TITLE
Reproduce the results in Table 2

### ISSUE THREAD

**Issue by goodbai-nlp** [dmelis/otalign#2]
Hi, I'm very interested in your work and trying to reproduce the results in your paper. On MUSE datasets,  I was able to get reasonable performance using the default parameters. 
However, when for dataset of Dinu et al. (2014), using the default parameters, the accuracy is very low (15.22% EN-IT). I also follow the paper to try different normalize metrics (mean, both, whiten, whiten_zca, none), it does not works for me.

python main_gw_bli.py --task dinu --src en --trg it --maxiter 2000 --normalize_vecs both

Any idea of what I might have done wrong?
Thank you.

**Comment by eyuansu62** [comment]
excuse me, could you please tell me where can i find the data files?

**Comment by dmelis** [comment]
@muyeby: the default parameters are meant for quick prototyping and short run times. To get higher quality results you'll need to set the --maxs and --maxt flags to larger values (e.g., 10K for those datasets). 

@eyuansu62: please don't post the same question on multiple issues.
