### ISSUE TITLE
1 issue and 1 suggestion in gw_optim

### ISSUE THREAD

**Issue by SimonPreissner** [dmelis/otalign#7]
I'm happy to use your code and I like doing so; it helps a lot. 
However, I've found two simple-to-fix issues:

1. [gw_optim.py#L581](https://github.com/dmelis/otalign/blob/master/src/gw_optim.py#L581): line 584 will throw an error if 'verbose' is False. Could the call to 'compute_gamma_entropy()' be moved to above the if-statement?

2. [gw_optim.py#L559](https://github.com/dmelis/otalign/blob/master/src/gw_optim.py#L559): the option 'print_every' is unused; could it replace the value '10' here?

**Comment by dmelis** [comment]
Thanks, I just fixed and pushed these changes.
